baseURL = 'https://additivemanufacturingguide.com/'
languageCode = 'en-us'
title = 'Additive Manufacturing Guide'
theme = 'pehtheme-hugo'

summaryLength = '20'

[params]
  description = 'Your go-to resource for 3D printing manufacturing â€” materials, techniques, industry insights, and production tips from the experts at Fabricatte.'
  mainSections = 'posts'
  defaultTheme = 'light'

[author]
  name = 'Fabricatte'
  bio = 'Expert insights on 3D printing manufacturing. Powered by Fabricatte, your digital manufacturing partner.'
  avatar = ''
  twitter = ''

[pagination]
  pagerSize = 6

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = 'Articles'
    pageRef = '/posts/'
    weight = 15
  [[menu.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 20
  [[menu.main]]
    name = 'Get a Quote'
    url = 'https://www.fabricatte.com/quote'
    weight = 25

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changeFreq = 'weekly'
  priority = 0.5

[taxonomies]
  tag = 'tags'
  category = 'categories'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts]
    source = 'assets'
    target = 'static'
